
import { Product, Language, Country } from './types';

// Helper to simulate dates relative to today
const getDateDaysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

// Helper to check if a product is a "New Release" (within 7 days)
export const isProductNew = (dateString: string): boolean => {
  const date = new Date(dateString);
  const now = new Date();
  const diffTime = Math.abs(now.getTime() - date.getTime());
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays <= 7;
};

export const PRODUCTS: Product[] = [
  // --- MEN (6 SKUs) ---
  {
    id: 'm1',
    name: 'StrideZero Phantom',
    category: 'men',
    price: 185,
    materialCost: 65,
    materials: ['Adaptive Knit', 'Carbon Fiber Plate', 'Rubber'],
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&q=80&w=800',
    colors: ['Black', 'Carbon'],
    sizes: [7, 8, 9, 10, 11, 12, 13],
    releaseDate: getDateDaysAgo(2), // New Release
    description: 'The ultimate stealth runner. Phantom features adaptive cushioning and a breathable knit upper.',
  },
  {
    id: 'm2',
    name: 'StrideZero Titan',
    category: 'men',
    price: 180,
    originalPrice: 210,
    materialCost: 70,
    materials: ['Reinforced Mesh', 'TPU Cage', 'EVA Foam'],
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800',
    colors: ['White', 'Platinum'],
    sizes: [8, 9, 10, 11, 12],
    releaseDate: getDateDaysAgo(45),
    description: 'Heavy-duty training support with a featherlight feel. Reinforced for maximum stability.',
  },
  {
    id: 'm3',
    name: 'StrideZero Onyx',
    category: 'men',
    price: 160,
    materialCost: 55,
    materials: ['Synthetic Leather', 'Foam Midsole'],
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=800',
    colors: ['Black'],
    sizes: [7, 8, 9, 10, 11, 12],
    releaseDate: getDateDaysAgo(30),
    description: 'Sleek, all-black aesthetic for the urban athlete. Seamless transitions from gym to street.',
  },
  {
    id: 'm4',
    name: 'StrideZero Vortex',
    category: 'men',
    price: 230,
    materialCost: 90,
    materials: ['Aerospace Mesh', 'Carbon Plate', 'Zoom Foam'],
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&q=80&w=800',
    colors: ['Platinum', 'Black'],
    sizes: [8, 9, 10, 11, 12],
    releaseDate: getDateDaysAgo(5), // New Release
    description: 'Maximum energy return for elite marathon runners. Carbon-plated propulsion.',
  },
  {
    id: 'm5',
    name: 'Platinum Tech Tee',
    category: 'men',
    price: 55,
    materialCost: 15,
    materials: ['Recycled Polyester', 'Elastane'],
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800',
    colors: ['Platinum', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    releaseDate: getDateDaysAgo(20),
    description: 'Advanced moisture-wicking fabric in our signature platinum hue. Athletic fit.',
  },
  {
    id: 'm6',
    name: 'Core Black Tee',
    category: 'men',
    price: 35,
    originalPrice: 45,
    materialCost: 10,
    materials: ['Organic Cotton'],
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&q=80&w=800',
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    releaseDate: getDateDaysAgo(60),
    description: 'Essential training tee. Lightweight, breathable, and designed for movement.',
  },

  // --- WOMEN (6 SKUs) ---
  {
    id: 'w1',
    name: 'StrideZero Luna',
    category: 'women',
    price: 175,
    materialCost: 60,
    materials: ['Lunar Foam', 'Engineered Mesh'],
    image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&q=80&w=800',
    colors: ['White', 'Platinum'],
    sizes: [5, 6, 7, 8, 9, 10],
    releaseDate: getDateDaysAgo(1), // New Release
    description: 'Defy gravity with the Luna. High-rebound foam meets a sculpted, aerodynamic silhouette.',
  },
  {
    id: 'w2',
    name: 'StrideZero Nova',
    category: 'women',
    price: 130,
    originalPrice: 155,
    materialCost: 45,
    materials: ['Mesh Upper', 'Rubber Sole'],
    image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&q=80&w=800',
    colors: ['Black', 'Silver'],
    sizes: [5, 6, 7, 8, 9],
    releaseDate: getDateDaysAgo(90),
    description: 'Versatile training shoe designed for high-intensity interval training.',
  },
  {
    id: 'w3',
    name: 'StrideZero Stellar',
    category: 'women',
    price: 195,
    materialCost: 75,
    materials: ['Primeknit', 'Boost Foam'],
    image: 'https://images.unsplash.com/photo-1571601335722-3a7a97217319?auto=format&fit=crop&q=80&w=800',
    colors: ['Platinum', 'White'],
    sizes: [6, 7, 8, 9],
    releaseDate: getDateDaysAgo(15),
    description: 'Premium cushioning for long-distance comfort without compromising style.',
  },
  {
    id: 'w4',
    name: 'StrideZero Aurora',
    category: 'women',
    price: 140,
    materialCost: 50,
    materials: ['Nylon', 'Phylon Midsole'],
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&q=80&w=800',
    colors: ['White', 'Black'],
    sizes: [6, 7, 8, 9],
    releaseDate: getDateDaysAgo(30),
    description: 'Lightweight everyday runner with a minimalist aesthetic.',
  },
  {
    id: 'w5',
    name: 'Aero Cropped Tee',
    category: 'women',
    price: 48,
    materialCost: 12,
    materials: ['Micro-Mesh', 'Spandex'],
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800',
    colors: ['White', 'Platinum'],
    sizes: ['XS', 'S', 'M', 'L'],
    releaseDate: getDateDaysAgo(3), // New Release
    description: 'Boxy, cropped fit for ventilation and style. Pairs perfectly with high-waisted leggings.',
  },
  {
    id: 'w6',
    name: 'Flow Motion Tunic',
    category: 'women',
    price: 52,
    materialCost: 14,
    materials: ['Bamboo Rayon', 'Cotton'],
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=800',
    colors: ['Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    releaseDate: getDateDaysAgo(10),
    description: 'Elongated silhouette with side slits for unrestricted movement during yoga or recovery.',
  },

  // --- KIDS (5 SKUs) ---
  {
    id: 'k1',
    name: 'StrideZero Comet',
    category: 'kids',
    price: 85,
    materialCost: 25,
    materials: ['Durable Mesh', 'Rubber'],
    image: 'https://images.unsplash.com/photo-1514989940723-e8875ea6ab7d?auto=format&fit=crop&q=80&w=800',
    colors: ['Black', 'White'],
    sizes: [1, 2, 3, 4, 5],
    releaseDate: getDateDaysAgo(60),
    description: 'Durability meets speed for the next generation of athletes.',
  },
  {
    id: 'k2',
    name: 'StrideZero Orbit',
    category: 'kids',
    price: 75,
    originalPrice: 90,
    materialCost: 22,
    materials: ['Canvas', 'Rubber'],
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&q=80&w=800',
    colors: ['White', 'Silver'],
    sizes: [1, 2, 3, 4, 5],
    releaseDate: getDateDaysAgo(100),
    description: 'All-day comfort for active play and sports. Reinforced toe cap.',
  },
  {
    id: 'k3',
    name: 'StrideZero Meteor',
    category: 'kids',
    price: 80,
    materialCost: 24,
    materials: ['Stretch Knit', 'Foam'],
    image: 'https://images.unsplash.com/photo-1519415943484-9fa1873496d4?auto=format&fit=crop&q=80&w=800',
    colors: ['Platinum', 'Black'],
    sizes: [1, 2, 3, 4, 5],
    releaseDate: getDateDaysAgo(6), // New Release
    description: 'Lightweight slip-on design for easy on and off.',
  },
  {
    id: 'k4',
    name: 'Junior Graphic Tee',
    category: 'kids',
    price: 35,
    materialCost: 8,
    materials: ['Cotton Blend'],
    image: 'https://images.unsplash.com/photo-1519238263496-6361937a42d8?auto=format&fit=crop&q=80&w=800',
    colors: ['White', 'Black'],
    sizes: ['S', 'M', 'L'],
    releaseDate: getDateDaysAgo(20),
    description: 'Soft cotton blend featuring the iconic StrideZero bolt logo.',
  },
  {
    id: 'k5',
    name: 'Active Play Jersey',
    category: 'kids',
    price: 38,
    materialCost: 9,
    materials: ['Polyester Mesh'],
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=800',
    colors: ['Platinum'],
    sizes: ['S', 'M', 'L'],
    releaseDate: getDateDaysAgo(40),
    description: 'Breathable mesh fabric for high-energy activities.',
  },

  // --- JEWELRY / ACCESSORIES (5 SKUs) ---
  {
    id: 'a1',
    name: 'Platinum Curb Chain',
    category: 'accessories',
    price: 450,
    materialCost: 320,
    materials: ['Solid Platinum', 'Rhodium Coating'],
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&q=80&w=800',
    colors: ['Platinum'],
    sizes: ['20"', '22"', '24"'],
    releaseDate: getDateDaysAgo(4), // New Release
    description: 'Solid platinum curb chain. The ultimate statement of luxury and endurance.',
  },
  {
    id: 'a2',
    name: 'SZ Diamond Pendant',
    category: 'accessories',
    price: 850,
    materialCost: 600,
    materials: ['Platinum', 'VS1 Diamond (0.5ct)'],
    image: 'https://images.unsplash.com/photo-1599643478518-17488fbbcd75?auto=format&fit=crop&q=80&w=800',
    colors: ['Diamond'],
    sizes: ['One Size'],
    releaseDate: getDateDaysAgo(120),
    description: 'A solitaire diamond set in platinum. Understated elegance for the finish line.',
  },
  {
    id: 'a3',
    name: 'SZ Gold Rope Chain',
    category: 'accessories',
    price: 380,
    materialCost: 250,
    materials: ['18k Gold'],
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=800',
    colors: ['Gold'],
    sizes: ['20"', '22"'],
    releaseDate: getDateDaysAgo(10),
    description: 'Classic rope design in 18k solid gold. Durable, timeless, and built to last.',
  },
  {
    id: 'a4',
    name: 'Onyx Signet Ring',
    category: 'accessories',
    price: 220,
    materialCost: 90,
    materials: ['Sterling Silver', 'Black Onyx'],
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800',
    colors: ['Silver/Black'],
    sizes: ['7', '8', '9', '10'],
    releaseDate: getDateDaysAgo(60),
    description: 'Bold signet ring featuring a flat black onyx stone set in polished silver.',
  },
  {
    id: 'a5',
    name: 'Diamond Nose Ring',
    category: 'accessories',
    price: 120,
    materialCost: 50,
    materials: ['14k White Gold', 'Diamond Chip'],
    image: 'https://images.unsplash.com/photo-1616428753235-901b0f585974?auto=format&fit=crop&q=80&w=800',
    colors: ['White Gold'],
    sizes: ['20G', '18G'],
    releaseDate: getDateDaysAgo(5), // New Release
    description: 'Subtle sparkle. A delicate diamond stud set in hypoallergenic 14k white gold.',
  },

  // --- SKATE GEAR (4 SKUs) ---
  {
    id: 's1',
    name: 'StrideZero Flip',
    category: 'skate',
    price: 95,
    materialCost: 35,
    materials: ['Premium Suede', 'Vulcanized Rubber', 'Impact Foam'],
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800',
    colors: ['Black/White', 'Navy/Gum'],
    sizes: [6, 7, 8, 9, 10, 11, 12],
    releaseDate: getDateDaysAgo(3),
    description: 'Suede finish with reinforced stitching and impact protection. Designed for durability and board feel.',
  },
  {
    id: 's2',
    name: 'Impact Heavy Hoodie',
    category: 'skate',
    price: 85,
    materialCost: 28,
    materials: ['Heavyweight Cotton', 'Fleece Lining'],
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800',
    colors: ['Black', 'Grey'],
    sizes: ['M', 'L', 'XL'],
    releaseDate: getDateDaysAgo(14),
    description: 'Oversized fit with reinforced stitching at stress points. Built to withstand the pavement.',
  },
  {
    id: 's3',
    name: 'Pro Deck 8.0',
    category: 'skate',
    price: 65,
    materialCost: 20,
    materials: ['7-Ply Maple'],
    image: 'https://images.unsplash.com/photo-1566453838084-5a3952a5595e?auto=format&fit=crop&q=80&w=800',
    colors: ['Natural'],
    sizes: ['8.0', '8.25', '8.5'],
    releaseDate: getDateDaysAgo(5),
    description: 'Canadian Maple 7-ply construction with high concave for massive pop.',
  },
  {
    id: 's4',
    name: 'Ceramic Bearings Set',
    category: 'skate',
    price: 45,
    materialCost: 15,
    materials: ['Ceramic', 'Steel'],
    image: 'https://images.unsplash.com/photo-1520045818171-5634d569661e?auto=format&fit=crop&q=80&w=800',
    colors: ['White'],
    sizes: ['Standard'],
    releaseDate: getDateDaysAgo(30),
    description: 'High-speed ceramic bearings that resist heat and friction. Pre-lubricated.',
  },

  // --- ELECTRONICS (9 SKUs) - Includes Laptops and High-End Tech ---
  {
    id: 'e1',
    name: 'TitanBook Pro',
    category: 'electronics',
    price: 1899,
    materialCost: 900,
    materials: ['Aluminum', 'Silicon', 'Glass'],
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca4?auto=format&fit=crop&q=80&w=800',
    colors: ['Silver', 'Space Gray'],
    sizes: ['14"', '16"'],
    releaseDate: getDateDaysAgo(1),
    description: 'Ultimate performance for creatives. M3 Max chip, Liquid Retina display.',
  },
  {
    id: 'e2',
    name: 'Sonic Over-Ear ANC',
    category: 'electronics',
    price: 349,
    materialCost: 120,
    materials: ['Plastic', 'Leather', 'Copper'],
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800',
    colors: ['Black', 'Platinum'],
    sizes: ['One Size'],
    releaseDate: getDateDaysAgo(15),
    description: 'Industry-leading noise cancellation. 40-hour battery life.',
  },
  {
    id: 'e3',
    name: 'SmartLink Watch 7',
    category: 'electronics',
    price: 499,
    materialCost: 200,
    materials: ['Titanium', 'Sapphire Glass'],
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
    colors: ['Titanium'],
    sizes: ['45mm', '49mm'],
    releaseDate: getDateDaysAgo(8),
    description: 'Rugged titanium case. Precision GPS and dive computer capabilities.',
  },
  {
    id: 'e4',
    name: 'Vision Phone X',
    category: 'electronics',
    price: 999,
    materialCost: 400,
    materials: ['Glass', 'Stainless Steel'],
    image: 'https://images.unsplash.com/photo-1592899677712-a1101f6968fd?auto=format&fit=crop&q=80&w=800',
    colors: ['Black', 'White', 'Gold'],
    sizes: ['256GB', '512GB'],
    releaseDate: getDateDaysAgo(60),
    description: 'Pro camera system. Super Retina XDR display.',
  },
  {
    id: 'e5',
    name: 'Tab Slate Air',
    category: 'electronics',
    price: 599,
    materialCost: 250,
    materials: ['Aluminum', 'Glass'],
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800',
    colors: ['Blue', 'Purple', 'Grey'],
    sizes: ['64GB', '256GB'],
    releaseDate: getDateDaysAgo(4),
    description: 'Impossibly thin. Incredibly powerful. The ultimate portable canvas.',
  },
  {
    id: 'e6',
    name: 'Mech Key Pro',
    category: 'electronics',
    price: 149,
    materialCost: 60,
    materials: ['PBT Plastic', 'Aluminum'],
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b91add1?auto=format&fit=crop&q=80&w=800',
    colors: ['RGB', 'White'],
    sizes: ['TKL', 'Full'],
    releaseDate: getDateDaysAgo(20),
    description: 'Tactile mechanical switches for precise typing and gaming.',
  },
  {
    id: 'e7',
    name: 'Pixel Mouse G',
    category: 'electronics',
    price: 89,
    materialCost: 30,
    materials: ['Plastic', 'PTFE'],
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800',
    colors: ['Black'],
    sizes: ['Standard'],
    releaseDate: getDateDaysAgo(25),
    description: 'Ultra-lightweight wireless gaming mouse with 25K sensor.',
  },
  {
    id: 'e8',
    name: 'Wireless Charge Pad',
    category: 'electronics',
    price: 49,
    materialCost: 15,
    materials: ['Silicone', 'Copper'],
    image: 'https://images.unsplash.com/photo-1616348436168-de43ad0db179?auto=format&fit=crop&q=80&w=800',
    colors: ['White', 'Black'],
    sizes: ['One Size'],
    releaseDate: getDateDaysAgo(5),
    description: 'Fast wireless charging for all your devices. MagSafe compatible.',
  },
  {
    id: 'e9',
    name: 'SkyStream Drone X',
    category: 'electronics',
    price: 1299,
    materialCost: 550,
    materials: ['Carbon Fiber', 'Plastic'],
    image: 'https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?auto=format&fit=crop&q=80&w=800',
    colors: ['White', 'Grey'],
    sizes: ['Standard'],
    releaseDate: getDateDaysAgo(2),
    description: '4K video, 10km range, and obstacle avoidance. Professional grade flight.',
  },

  // --- HOME GOODS (8 SKUs) - Includes Kitchen Content ---
  {
    id: 'h1',
    name: 'Damascus Chef Knife',
    category: 'home',
    price: 249,
    materialCost: 80,
    materials: ['VG10 Steel', 'Pakkawood'],
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&q=80&w=800',
    colors: ['Steel'],
    sizes: ['8 inch'],
    releaseDate: getDateDaysAgo(2),
    description: '67-layer Damascus steel blade for razor-sharp precision.',
  },
  {
    id: 'h2',
    name: 'Ironclad Skillet',
    category: 'home',
    price: 89,
    materialCost: 30,
    materials: ['Cast Iron'],
    image: 'https://images.unsplash.com/photo-1585501869811-f6089d813872?auto=format&fit=crop&q=80&w=800',
    colors: ['Black'],
    sizes: ['10 inch', '12 inch'],
    releaseDate: getDateDaysAgo(40),
    description: 'Pre-seasoned cast iron skillet. Heirloom quality.',
  },
  {
    id: 'h3',
    name: 'Espresso Barista Pro',
    category: 'home',
    price: 699,
    materialCost: 300,
    materials: ['Stainless Steel', 'Brass'],
    image: 'https://images.unsplash.com/photo-1574315042633-8c460d3d5402?auto=format&fit=crop&q=80&w=800',
    colors: ['Chrome'],
    sizes: ['Standard'],
    releaseDate: getDateDaysAgo(10),
    description: 'Café quality espresso at home. Integrated grinder and milk frother.',
  },
  {
    id: 'h4',
    name: 'Vortex Blender',
    category: 'home',
    price: 399,
    materialCost: 150,
    materials: ['Plastic', 'Steel Motor'],
    image: 'https://images.unsplash.com/photo-1570222094114-28a9d88a27e6?auto=format&fit=crop&q=80&w=800',
    colors: ['Black', 'Red'],
    sizes: ['64oz'],
    releaseDate: getDateDaysAgo(30),
    description: 'Commercial grade motor. Pulverizes ice and frozen fruit in seconds.',
  },
  {
    id: 'h5',
    name: 'Artisan Ceramic Set',
    category: 'home',
    price: 129,
    materialCost: 50,
    materials: ['Stoneware'],
    image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=800',
    colors: ['Matte Black', 'Stone Grey'],
    sizes: ['16 Piece'],
    releaseDate: getDateDaysAgo(60),
    description: 'Hand-finished stoneware dinner set. Microwave and dishwasher safe.',
  },
  {
    id: 'h6',
    name: 'Crystal Wine Glass Set',
    category: 'home',
    price: 89,
    materialCost: 30,
    materials: ['Lead-Free Crystal'],
    image: 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?auto=format&fit=crop&q=80&w=800',
    colors: ['Clear'],
    sizes: ['Set of 4'],
    releaseDate: getDateDaysAgo(15),
    description: 'Ultra-thin rim for an exquisite tasting experience. Bordeaux shape.',
  },
  {
    id: 'h7',
    name: 'Non-Stick Fry Pan',
    category: 'home',
    price: 79,
    materialCost: 25,
    materials: ['Aluminum', 'Ceramic Coating'],
    image: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&q=80&w=800',
    colors: ['Grey'],
    sizes: ['10 inch'],
    releaseDate: getDateDaysAgo(5),
    description: 'Toxin-free ceramic non-stick coating. Oven safe.',
  },
  {
    id: 'h8',
    name: 'Gold Flatware Set',
    category: 'home',
    price: 149,
    materialCost: 60,
    materials: ['Stainless Steel', 'Titanium Plating'],
    image: 'https://images.unsplash.com/photo-1581781870027-024c0428669b?auto=format&fit=crop&q=80&w=800',
    colors: ['Gold', 'Rose Gold'],
    sizes: ['20 Piece'],
    releaseDate: getDateDaysAgo(25),
    description: 'Modern silhouette with a durable matte gold finish.',
  },

  // --- GROCERY (12 SKUs) ---
  {
    id: 'g1',
    name: 'Single Origin Coffee',
    category: 'grocery',
    price: 22,
    materialCost: 8,
    materials: ['Arabica Beans'],
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=800',
    colors: ['Dark Roast'],
    sizes: ['12oz'],
    releaseDate: getDateDaysAgo(3),
    description: 'Ethically sourced single-origin beans. Notes of chocolate and cherry.',
  },
  {
    id: 'g2',
    name: 'Organic Matcha Powder',
    category: 'grocery',
    price: 35,
    materialCost: 12,
    materials: ['Green Tea'],
    image: 'https://images.unsplash.com/photo-1515825838458-f2a94b20105a?auto=format&fit=crop&q=80&w=800',
    colors: ['Green'],
    sizes: ['30g'],
    releaseDate: getDateDaysAgo(10),
    description: 'Ceremonial grade matcha from Uji, Japan.',
  },
  {
    id: 'g3',
    name: 'Raw Honey Comb',
    category: 'grocery',
    price: 18,
    materialCost: 6,
    materials: ['Honey', 'Wax'],
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800',
    colors: ['Golden'],
    sizes: ['200g'],
    releaseDate: getDateDaysAgo(20),
    description: 'Unfiltered raw honey with honeycomb.',
  },
  {
    id: 'g4',
    name: 'Artisan Sourdough',
    category: 'grocery',
    price: 12,
    materialCost: 3,
    materials: ['Flour', 'Water', 'Salt'],
    image: 'https://images.unsplash.com/photo-1585476644321-b97621c337c9?auto=format&fit=crop&q=80&w=800',
    colors: ['Brown'],
    sizes: ['Loaf'],
    releaseDate: getDateDaysAgo(1),
    description: 'Slow-fermented sourdough bread with a crispy crust.',
  },
  {
    id: 'g5',
    name: 'Extra Virgin Olive Oil',
    category: 'grocery',
    price: 28,
    materialCost: 10,
    materials: ['Olives'],
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcdccef?auto=format&fit=crop&q=80&w=800',
    colors: ['Green/Gold'],
    sizes: ['500ml'],
    releaseDate: getDateDaysAgo(40),
    description: 'Cold-pressed premium olive oil from Tuscany.',
  },
  {
    id: 'g6',
    name: 'Himalayan Pink Salt',
    category: 'grocery',
    price: 9,
    materialCost: 2,
    materials: ['Salt'],
    image: 'https://images.unsplash.com/photo-1626139576127-45884c45799a?auto=format&fit=crop&q=80&w=800',
    colors: ['Pink'],
    sizes: ['250g'],
    releaseDate: getDateDaysAgo(60),
    description: 'Mineral-rich coarse pink salt.',
  },
  {
    id: 'g7',
    name: 'Dark Chocolate 85%',
    category: 'grocery',
    price: 8,
    materialCost: 3,
    materials: ['Cacao', 'Cane Sugar'],
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&q=80&w=800',
    colors: ['Dark'],
    sizes: ['100g'],
    releaseDate: getDateDaysAgo(5),
    description: 'Intense dark chocolate with floral notes.',
  },
  {
    id: 'g8',
    name: 'Almond Milk Barista',
    category: 'grocery',
    price: 6,
    materialCost: 2,
    materials: ['Almonds', 'Water'],
    image: 'https://images.unsplash.com/photo-1600788886242-5c96aabe3757?auto=format&fit=crop&q=80&w=800',
    colors: ['White'],
    sizes: ['1L'],
    releaseDate: getDateDaysAgo(15),
    description: 'Creamy plant-based milk formulated for latte art.',
  },
  {
    id: 'g9',
    name: 'Organic Avocados',
    category: 'grocery',
    price: 10,
    materialCost: 4,
    materials: ['Avocado'],
    image: 'https://images.unsplash.com/photo-1523049673856-606ae7e1e5eb?auto=format&fit=crop&q=80&w=800',
    colors: ['Green'],
    sizes: ['Pack of 4'],
    releaseDate: getDateDaysAgo(2),
    description: 'Perfectly ripe organic Hass avocados.',
  },
  {
    id: 'g10',
    name: 'Whey Protein Isolate',
    category: 'grocery',
    price: 55,
    materialCost: 20,
    materials: ['Whey Isolate', 'Cocoa'],
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&q=80&w=800',
    colors: ['Chocolate'],
    sizes: ['2lb'],
    releaseDate: getDateDaysAgo(25),
    description: 'Fast-absorbing protein for muscle recovery.',
  },
  {
    id: 'g11',
    name: 'Sparkling Water',
    category: 'grocery',
    price: 18,
    materialCost: 5,
    materials: ['Water', 'CO2'],
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=800',
    colors: ['Lime'],
    sizes: ['12 Pack'],
    releaseDate: getDateDaysAgo(10),
    description: 'Refreshing sparkling water with natural lime essence.',
  },
  {
    id: 'g12',
    name: 'Hot Sauce Reserve',
    category: 'grocery',
    price: 14,
    materialCost: 4,
    materials: ['Ghost Pepper', 'Vinegar'],
    image: 'https://images.unsplash.com/photo-1588165171080-c89ac14294d1?auto=format&fit=crop&q=80&w=800',
    colors: ['Red'],
    sizes: ['5oz'],
    releaseDate: getDateDaysAgo(30),
    description: 'Small batch fermented hot sauce. Extreme heat.',
  }
];

export const CATEGORIES = ['men', 'women', 'kids', 'accessories', 'skate', 'electronics', 'home', 'grocery'];

// --- LOCALIZATION DATA ---

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    nav: { all: 'All', men: 'Men', women: 'Women', kids: 'Kids', accessories: 'Accessories', skate: 'Skate', electronics: 'Electronics', home: 'Home', grocery: 'Grocery' },
    hero: {
      title: 'DEFY',
      titleHighlight: 'GRAVITY.',
      subtitle: 'Engineered with aerospace-grade platinum accents and reactive carbon-fiber propulsion.',
      cta1: 'Shop The Drop',
      cta2: 'Explore Collection'
    },
    sections: {
      trending: 'New Releases',
      freshDrops: 'Fresh Drops'
    }
  },
  de: {
    nav: { all: 'Alle', men: 'Herren', women: 'Damen', kids: 'Kinder', accessories: 'Accessoires', skate: 'Skate', electronics: 'Elektronik', home: 'Zuhause', grocery: 'Lebensmittel' },
    hero: {
      title: 'SCHWERKRAFT',
      titleHighlight: 'BESIEGEN.',
      subtitle: 'Entwickelt mit Akzenten aus Platin und reaktivem Carbonfaser-Antrieb.',
      cta1: 'Jetzt Kaufen',
      cta2: 'Kollektion'
    },
    sections: {
      trending: 'Neuerscheinungen',
      freshDrops: 'Frische Drops'
    }
  },
  fr: {
    nav: { all: 'Tout', men: 'Hommes', women: 'Femmes', kids: 'Enfants', accessories: 'Accessoires', skate: 'Skate', electronics: 'Électronique', home: 'Maison', grocery: 'Épicerie' },
    hero: {
      title: 'DÉFIEZ',
      titleHighlight: 'LA GRAVITÉ.',
      subtitle: 'Conçu avec des accents en platine de qualité aérospatiale et une propulsion en fibre de carbone.',
      cta1: 'Acheter',
      cta2: 'Découvrir'
    },
    sections: {
      trending: 'Nouvelles Sorties',
      freshDrops: 'Nouveautés'
    }
  },
  ja: {
    nav: { all: 'すべて', men: 'メンズ', women: 'レディース', kids: 'キッズ', accessories: 'アクセサリー', skate: 'スケート', electronics: 'エレクトロニクス', home: 'ホーム', grocery: '食料品' },
    hero: {
      title: '重力を',
      titleHighlight: '超えろ。',
      subtitle: '航空宇宙グレードのプラチナアクセントと反応性カーボンファイバー推進力を搭載。',
      cta1: '今すぐ購入',
      cta2: 'コレクションを見る'
    },
    sections: {
      trending: '新着アイテム',
      freshDrops: '最新ドロップ'
    }
  }
};

// Map simulated country codes to specific tax rates
export const TAX_RATES: Record<Country, number> = {
  US: 0.0825, // 8.25%
  UK: 0.20,   // 20% VAT
  AU: 0.10,   // 10% GST
  NZ: 0.15,   // 15% GST
  DE: 0.19,   // 19% VAT
  IT: 0.22,   // 22% VAT
  FR: 0.20,   // 20% VAT
  CA: 0.13,   // 13% HST (avg)
  JP: 0.10,   // 10% Consumption Tax
  IN: 0.18    // 18% GST
};

export const CURRENCY_MAP: Record<Country, string> = {
  US: '$',
  UK: '£',
  AU: 'A$',
  NZ: 'NZ$',
  DE: '€',
  IT: '€',
  FR: '€',
  CA: 'C$',
  JP: '¥',
  IN: '₹'
};

export interface HolidayPromo {
  name: string;
  code: string;
  discount: string;
}

// Map simulated country to a specific holiday event
export const HOLIDAY_PROMOS: Record<Country, HolidayPromo> = {
  US: { name: 'Independence Day Sale', code: 'JULY4', discount: '20% OFF' },
  UK: { name: 'Boxing Day Warmup', code: 'BOXING', discount: '15% OFF' },
  AU: { name: 'Summer Solstice Event', code: 'SUNNY', discount: 'Free Shipping' },
  NZ: { name: 'Waitangi Weekend', code: 'KIWI', discount: '10% OFF' },
  DE: { name: 'Oktoberfest Special', code: 'PROST', discount: 'Buy 1 Get 1 50% Off' },
  IT: { name: 'Ferragosto Sale', code: 'SUMMER', discount: '20% OFF' },
  FR: { name: 'Bastille Day Event', code: 'LIBERTE', discount: '25% OFF' },
  CA: { name: 'Canada Day Special', code: 'EH20', discount: '20% OFF' },
  JP: { name: 'Golden Week', code: 'GOLD', discount: '¥2000 OFF' },
  IN: { name: 'Diwali Festival of Lights', code: 'LIGHTS', discount: '30% OFF' }
};
